---
- name: download tomcat zip
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
    dest: /root/
- name: create a file for tomcat
  file:
    dest: /opt/tomcat
    state: directory
    mode: u+rwx,g+rwx,o+rwx
- name: unzip tomcat
  unarchive:
    src: /root/apache-tomcat-9.0.89.tar.gz
    dest: /opt/tomcat
    remote_src: yes
- name: start tomcat
  command: nohup /opt/tomcat/apache-tomcat-9.0.89/bin/startup.sh
  args:
    chdir: /opt/tomcat/apache-tomcat-9.0.89/bin

